<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\integration-tests.props" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime.Serialization.JsonNet" />
    <PackageReference Include="TestContainers.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="FluentAssertions.Nodatime" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Agenda.API\Agenda.API.csproj" />
    
  </ItemGroup>

</Project>