<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\tests.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="MartinCostello.Logging.XUnit.v3"/>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Agenda.API\Agenda.API.csproj" />
    <ProjectReference Include="..\..\src\Agenda.AppHost\Agenda.AppHost.csproj" />
    <ProjectReference Include="..\Agenda.UnitTests.Helpers\Agenda.UnitTests.Helpers.csproj" />
  </ItemGroup>
</Project>