version: '3.4'

services:
  agenda.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - CONNECTIONSTRINGS__AGENDA=Server=agenda.db;Database=agenda;User ID=postgres;Password=P4ssW0rd!
    ports:
      - "80"
#      - "443"
#    volumes:
#      - /root/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
#      - /root/.aspnet/https:/root/.aspnet/https:ro
  agenda.db:
    environment:
      POSTGRES_PASSWORD: P4ssW0rd!
    ports:
      - "6000:5432"
