<Project>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsIntegrationTestProject>false</IsIntegrationTestProject>
    <IsIntegrationTestProject Condition="$(MSBuildProjectName.EndsWith('IntegrationTests'))">true</IsIntegrationTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <!-- Exclude tests from code coverage analysis-->
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Xunit.OpenCategories.V3" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="NodaTime.Bogus" />
    <PackageReference Include="NodaTime.Testing" />
    <PackageReference Include="FsCheck.Xunit.v3" />

    <PackageReference Include="Moq" />
    <PackageReference Include="AutoFixture.AutoFakeItEasy" />
    <PackageReference Include="coverlet.msbuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>