<Project>
  <Import Project="core.props"/>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsIntegrationTestProject>false</IsIntegrationTestProject>
    <IsIntegrationTestProject Condition="$(MSBuildProjectName.EndsWith('IntegrationTests'))">true</IsIntegrationTestProject>
  </PropertyGroup>

  <!-- Exclude tests from code coverage analysis-->
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AwesomeAssertions"/>
    <PackageReference Include="Bogus"/>
    <PackageReference Include="coverlet.msbuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FakeItEasy"/>
    <PackageReference Include="FsCheck.Xunit"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="NodaTime.Bogus"/>
    <PackageReference Include="NodaTime.Testing"/>
    <PackageReference Include="Serialize.Linq" />
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.categories"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
  </ItemGroup>
  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>
</Project>