<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\tests.props" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net8.0'">
    <ProjectReference Include="..\..\src\Agenda.API\Agenda.API.csproj" />
  </ItemGroup>

</Project>