<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\tests.props"/>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" Version="0.12.1"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Agenda.API\Agenda.API.csproj" />
  </ItemGroup>

</Project>