<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\tests.props" />
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Agenda.Objects\Agenda.Objects.csproj" />
    <ProjectReference Include="..\Agenda.UnitTests.Helpers\Agenda.UnitTests.Helpers.csproj" />
  </ItemGroup>

</Project>