<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../core.props"/>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Candoumbe.DataAccess.EFStore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Agenda.Objects\Agenda.Objects.csproj" />
  </ItemGroup>

</Project>