<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../core.props"/>
  <PropertyGroup>
    <TargetFrameworks>net8;net9.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Paramore.Brighter" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Agenda.Ids\Agenda.Ids.csproj" />
  </ItemGroup>
</Project>