<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\tests.props" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Agenda.API\Agenda.API.csproj" />
    <ProjectReference Include="..\Agenda.UnitTests.Helpers\Agenda.UnitTests.Helpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Appointments\" />
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>